export const GET_DOMAINS = 'GET_DOMAINS';
export const GET_SINGLE_DOMAIN = 'GET_SINGLE_DOMAIN';
export const ADD_DOMAIN = 'ADD_DOMAIN';
export const UPDATE_DOMAIN = 'UPDATE_DOMAIN';
export const DELETE_DOMAIN = 'DELETE_DOMAIN';
